### ISSUE TITLE
[Bug Report] Removed gymnasium logging type in `dataset.minari_dataset`

### ISSUE THREAD

**Issue by moripiri** [Farama-Foundation/Minari#260]
**Describe the bug**
Cannot recover gymnasium environment with `eval_env=True`.

**Code example**
```
import minari

dataset = minari.load_dataset("mujoco/ant/expert-v0")
env = dataset.recover_environment(eval_env=True)
```

Error message
```
  File "/Users/moripiri/Library/Caches/pypoetry/virtualenvs/diverserl-tQKqZcEi-py3.12/lib/python3.12/site-packages/minari/dataset/minari_dataset.py", line 211, in recover_environment
    logger.info(
    ^^^^^^^^^^^
AttributeError: module 'gymnasium.logger' has no attribute 'info'
```

**System Info**
Describe the characteristic of your environment:
 * Describe how Minari was installed: pip, version 0.5.1
 * Operating system: macOS Sequoia 15.1 
 * Python version: 3.12

**Additional context**
Gymnasium commit that deleted `gymnasium.logger.info`: https://github.com/Farama-Foundation/Gymnasium/commit/992638e120a587e5673030c2e6b81f937440e625

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Minari/issues) in the repo (**required**)

**Comment by younik** [comment]
Hi @moripiri, thanks for the issue

I believe we fixed it in the main branch, but we didn't release a new version yet (we will soon).
Can you check if installing Minari with `pip install git+https://github.com/Farama-Foundation/Minari.git` solves the issue?

**Comment by moripiri** [comment]
Hi @younik , thanks for quick reply.

I confirmed that installing Minari with pip install git+https://github.com/Farama-Foundation/Minari.git solved the aforementioned issue, and the issue still remaining when installed with `pip install minari`.
